export default class screenNames{
    static HOME_SCREEN = "home"
    static LOGIN_SCREEN = "login"
    static FORGOT_PWD_SCREEN = "forgotPwd";
    static RESET_PWD_SCREEN = "resetPwd";
    static NEW_ACCT_SCREEN = "makeAccount"
    static VERIFY_ACCT_SCREEN = "verifyAccount"
    static WRITE_SCREEN = "write"
    static WRITE_SCREEN_FRAME = "writeF"
    static READ_SCREEN = "read"
    static READ_SCREEN_FRAME = "readF";
    static INITIALIZER_SCREEN = "loading";
    static AUTH_NAVIGATION = "Auth"
    static APP_NAVIGATION = "App"
    static OPTIONS_MENU = "Options"
    static OPTIONS_MENU_INTERIOR = "OptionsMenu";
    static JOURNAL_TAB_SCREEN = "JournalTab";
    static WRITE_SCREEN_DRAWER_FRAME = "WriteDrawer";
    static READ_SCREEN_DRAWER_FRAME = "ReadDrawer";
}
